### PR TITLE
Initial Project

### PR DESCRIPTION
**Pull request by phudv-0958**
===> Title: Initial Project

===> Redmine Ticket: https://edu-redmine.sun-asterisk.vn/issues/18873

===> Attachment Files: 
image

### CODE REVIEW

**Comment by phudv-0958** [comment]
ready

**Comment by phudv-0958** [comment]
ready

**Comment by phudv-0958** [comment]
ready

**Comment by hungct-1121** [comment]
ready

**Comment by phudv-0958** [comment]
vâng anh =)

**Pull request merged**
